### PR TITLE
Added random seeds to functions

### PR DESCRIPTION
**Pull request by fredtony**
I believe I caught most of the functions with randomness and added params to minimize stochasticity, but open to feedback if there are other places that I missed. Thanks!

### CODE REVIEW

**Review by hesther — COMMENTED** [review]
I think this looks really good, thanks! Since you included a random seed also in the MC routine, I think it would be nice to pass the seed to the GetEspSim() function as well (in addition to the embedding routines), which in turn can pass it to the MC routine, since otherwise the seed in the MC routine will always be the default value. Would you be able to still include that?

**Comment by fredtony** [comment]
Ah, good point. I’ll add that in!

**Comment by fredtony** [comment]
I think I covered all of those function calls, but let me know if I missed anything though.

**Review by hesther — APPROVED** [review]
Looks great, going to merge this in a sec. Thank you very much for contributing!

**Comment by hesther** [comment]
Just pushed a hotfix since the randomseed broke on of the function calls - dang, I should really introduce automated tests.

**Comment by fredtony** [comment]
@hesther Ah, apologies, I my dev machine and the machine I use it on are different, so I didn't test it out. I saw your hotfix and if you want to stick with ETKDGv2, the only thing I might consider additionally updating is `AllChem.EmbedMultipleConfs(prbMol, prbNumConfs, ETversion=2, randomSeed=randomseed)` (I double checked and the rest of the params are the same) or
```
params = ETKDGv2()
params.randomSeed = randomseed
AllChem.EmbedMultipleConfs(prbMol, prbNumConfs, params)
```
I double checked both and they both seem to product identical results (and not stochastic 😄). Thanks again for your work!

**Comment by hesther** [comment]
No problem at all! (Also, this is on me for not writing proper unit tests, which I just moved up from my todo list). I think I will need to think about which settings to use for the embedding, since previously it was a bit inconsistent (ETKDGv2 was used for regular embedding, but not for constrained) - so for now I just changed it to version 1 for everything. I will have to run some tests which routine produces better results (or feel free to run some tests if you have time!)

**Pull request merged**
